# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'email.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\x05\x65mail\"\x1c\n\x0cQueryRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\rReplyResponse\x12\r\n\x05reply\x18\x01 \x01(\t2G\n\x0c\x45mailService\x12\x37\n\nDraftReply\x12\x13.email.QueryRequest\x1a\x14.email.ReplyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=22
  _globals['_QUERYREQUEST']._serialized_end=50
  _globals['_REPLYRESPONSE']._serialized_start=52
  _globals['_REPLYRESPONSE']._serialized_end=82
  _globals['_EMAILSERVICE']._serialized_start=84
  _globals['_EMAILSERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
